using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace NT3 {
	public class GlobalValues : Singelton<GlobalValues> {

		public bool m_autoGenerated = true;

		public GameObject[] p_objectTypes = null;

		public int m_lockStepBufferSize = 6;

		private void Start() {
			if (m_autoGenerated) {
				Debug.LogError("Global Values where automaticly generated");
				return;
			}
		}
	}
}