using System.Collections;
using System.Collections.Generic;
using System.Net;
using UnityEngine;
using System.Text;

namespace PPBA
{
	public class client
	{
		public int _id;
		public bool _isConnected = false;
		public IPEndPoint _ep;
		public RingBuffer<InputState> _inputStates = new RingBuffer<InputState>();
		public RingBuffer<GameState> _gameStates = new RingBuffer<GameState>();

		public client()
		{
			_inputStates[0] = new InputState();
			_gameStates[0] = new GameState();
		}

		public override string ToString()
		{
			StringBuilder sb = new StringBuilder();
			sb.AppendLine(base.ToString());
			sb.AppendLine("id: " + _id.ToString());
			sb.AppendLine("is Connected: " + _isConnected.ToString());
			sb.AppendLine("endPoint: " + (_ep == null ? "NON" : _ep.ToString()));
			sb.AppendLine("Input State: " + (_inputStates == null ? "NON" : _inputStates.ToString()));
			sb.AppendLine("Game State: " + (_gameStates == null ? "NON" : _gameStates.ToString()));

			return sb.ToString();
		}
	}

	public class GlobalVariables : Singleton<GlobalVariables>
	{
		#region Variables

		public List<client> _clients = new List<client>();

		[Tooltip("deactivate this bool to signivy that this variables where set by us")]
		[SerializeField] private bool _autoGenerated = true;

		public GameObject[] _prefabs;

		#endregion
		#region MonoBehaviour

		void Start()
		{
			//place variables or calculations that have to be set/done here
#if !UNITY_SERVER
			{
				client tmp = new client();
				_clients.Insert(0, tmp);
			}
#endif

			if(_autoGenerated)
			{
				Debug.LogError("Global Values where automaticly generated");
				return;
			}

			//place variables or calculation that must not be set or done if it is autogenerated
			DontDestroyOnLoad(this.gameObject);
		}

		#endregion
	}
}