using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace PPBA
{
	public class GlobalVariables : Singleton<GlobalVariables>
	{
		#region Variables

		[Tooltip("deactivate this bool to signivy that this variables where set by us")]
		[SerializeField] private bool _autoGenerated = true;

		#endregion
		#region MonoBehaviour

		void Start()
		{
			//place variables or calculations that have to be set/done here


			if(_autoGenerated)
			{
				Debug.LogError("Global Values where automaticly generated");
				return;
			}

			//place variables or calculation that must not be set or done if it is autogenerated
			DontDestroyOnLoad(this.gameObject);
		}

		#endregion
	}
}